export const ICONS = {
  ARROW_DOWN_GRAY: 'assets/icons/sort-arrow-down-gray-500.svg',
  ARROW_LEFT: 'assets/icons/arrow-left-outline.svg',
  ARROW_LEFT_GRAY: 'assets/icons/chevron-left-outline-gray-500.svg',
  ARROW_RIGHT_GRAY: 'assets/icons/chevron-right-outline-gray-500.svg',
  AWARD: 'assets/icons/award-outline.svg',
  BAN_RED: 'assets/icons/ban-outline-red-500.svg',
  BAR_CHART_BLUE: 'assets/icons/bar-chart-2-outline-blue-500.svg',
  BAR_CHART_GRAY: 'assets/icons/bar-chart-2-outline-gray-500.svg',
  BOOK_OUTLINE_GRAY: 'assets/icons/book-outline-gray-500.svg',
  CALENDAR_OUTLINE_GRAY_500: 'assets/icons/calendar-outline-gray-500.svg',
  CAST_BLUE: 'assets/icons/cast-outline-blue-500.svg',
  CHECK_BLUE: 'assets/icons/check-outline-blue-500.svg',
  CHECK_CIRCLE_GREEN: 'assets/icons/check-circle-solid-green-500.svg',
  CHECK_GREEN: 'assets/icons/check-outline-green-500.svg',
  CHECK_WHITE: 'assets/icons/check-outline-white.svg',
  CLIPBOARD_LIST: 'assets/icons/clipboard-list.svg',
  COPY_CLIPBOARD: 'assets/icons/copy-clipboard-outline-gray-500.svg',
  DOWNLOAD_BLUE: 'assets/icons/download-outline-blue.svg',
  DOWNLOAD_OUTLINE_WHITE: 'assets/icons/download-outline-white.svg',
  EXCLAMATION_CIRCLE_RED: 'assets/icons/exclamation-circle-solid-red-500.svg',
  EXTERNAL_LINK_BLUE: 'assets/icons/external-link-outline-outline-blue-500.svg',
  FIRE_CLUSTER_RED_HIGH: 'assets/icons/map/ic-fire-map-cluster-high.svg',
  FIRE_CLUSTER_RED_MEDIUM: 'assets/icons/map/ic-fire-map-cluster-medium.svg',
  FIRE_GRAY: 'assets/icons/map/fire-solid-gray-300.svg',
  FIRE_RED_HIGH: 'assets/icons/map/ic-fire-map-pin-high.svg',
  FIRE_RED_LOW: 'assets/icons/map/ic-fire-map-pin-low.svg',
  FIRE_RED_MEDIUM: 'assets/icons/map/ic-fire-map-pin-medium.svg',
  HORIZONTAL_DOTS: 'assets/icons/dots-horizontal-outline-gray-500.svg',
  INDOOR_BLUE: 'assets/icons/indoor-solid-blue-500.svg',
  INDOOR_GRAY: 'assets/icons/indoor-solid-gray-500.svg',
  KEY_BLUE: 'assets/icons/key-outline-blue-500.svg',
  LIGHTNING_BLUE: 'assets/icons/lightning-bolt-outline-blue-500.svg',
  LOCATION_MARKER_BLUE: 'assets/icons/location-marker-solid-blue-500.svg',
  LOCATION_MARKER_GRAY: 'assets/icons/location-marker-solid-gray-500.svg',
  LOCATION_MARKER_OUTLINE_GRAY:
    'assets/icons/location-marker-outline-gray-500.svg',
  MAIL_BLUE: 'assets/icons/mail-open-outline-blue-500.svg',
  MAXIMIZE: 'assets/icons/map/maximize-outline-gray-500.svg',
  MINUS_GRAY: 'assets/icons/minus-sm-outline-gray-500.svg',
  NEW_TAB_ICON: 'assets/icons/open-new-tab-icon-blue-500.svg',
  OUTDOOR_BLUE: 'assets/icons/outdoor-solid-blue-500.svg',
  OUTDOOR_GRAY: 'assets/icons/outdoor-solid-gray-500.svg',
  PENCIL_GRAY: 'assets/icons/pencil-outline-gray-500.svg',
  PLUS_BLACK: 'assets/icons/plus-outline-black.svg',
  PLUS_BLUE: 'assets/icons/plus-outline-blue-500.svg',
  PLUS_GRAY: 'assets/icons/plus-outline-gray-500.svg',
  PLUS_RED: 'assets/icons/plus-outline-red-500.svg',
  PLUS_WHITE: 'assets/icons/plus-outline-white.svg',
  QUESTION_MARK_CIRCLE_GRAY:
    'assets/icons/question-mark-circle-solid-gray-400.svg',
  QUESTION_MARK_CIRCLE_GRAY_500:
    'assets/icons/question-mark-circle-outline-gray-500.svg',
  SERVER_BLUE: 'assets/icons/server-outline-blue-500.svg',
  SERVER_GRAY: 'assets/icons/server-outline-gray-500.svg',
  SETTINGS_GRAY: 'assets/icons/cog-outline-gray-500.svg',
  STATION_GRAY: 'assets/icons/station-outline-gray-500.svg',
  STATION_PENDING_BLUE: 'assets/icons/station-pending-outline-blue-500.svg',
  STATION_PUBLISHED_BLUE: 'assets/icons/station-published-blue-500.svg',
  STATION_UNPUBLISHED_BLUE:
    'assets/icons/station-unpublished-outline-blue-500.svg',
  THREE_LAYER_BLUE: 'assets/icons/3-layers-outline-blue-500.svg',
  THREE_LAYER_GRAY: 'assets/icons/3-layers-outline-gray-500.svg',
  TRIANGLE_EXCLAMATION: 'assets/icons/exclamation-solid-red-500.svg ',
  TRIANGLE_EXCLAMATION_OUTLINE_WHITE:
    'assets/icons/exclamation-outline-white.svg',
  USERS_OUTLINE_BLUE: 'assets/icons/users-outline-blue-500.svg',
  VERTICAL_DOTS: 'assets/icons/dots-vertical-outline-gray-500.svg',
  WARNING_CIRCLE_BLUE: 'assets/icons/exclamation-circle-outline-blue-500.svg',
  WARNING_CIRCLE_RED: 'assets/icons/exclamation-circle-outline-red-500.svg',
  WARNING_ORANGE: 'assets/icons/exclamation-outline-orange-500.svg',
  WARNING_RED: 'assets/icons/exclamation-solid-red-500.svg',
  WYSIWYG_BOLD: 'assets/icons/bold-wysiwyg-icon.svg',
  WYSIWYG_ITALIC: 'assets/icons/italic-wysiwyg-icon.svg',
  WYSIWYG_UNORDERED_LIST: 'assets/icons/unordered-list-wysiwyg-icon.svg',
  X_CIRCLE_RED: 'assets/icons/x-circle-solid-red-500.svg',
  X_GRAY: 'assets/icons/x-outline-gray-500.svg',
  X_WHITE: 'assets/icons/x-outline-white.svg',
} as const;
